refactor log analysis
gurtanvi/log_analysis pull request #1
Opened 2021-08-24 12:17 UTC by gurtanvi

add .gitignore
refactor log_analysis

2021-08-24 17:40 UTC, madhavhugar commented on log.py
> +#df_logfile = create_log_df('/home/gurleenkaur/Programming/log_analysis/data/logs.log')
uncomment this line 

```python
df_logfile = create_log_df('/home/gurleenkaur/Programming/log_analysis/data/logs.log')
```
`df_logfile` would be a dataframe with 3 columns `name`, `type`, and `duration`

you are headed in the right direction. Once you have the dataframe apply some pandas magic to get the expected results 🧙

2021-08-27 16:03 UTC, madhavhugar requested changes

2021-08-27 16:03 UTC, madhavhugar commented on log.py
> +print(df_logfile)
Maybe you missed to commit the answers to the questions? :)

2021-08-27 16:03 UTC, madhavhugar commented on log.py
> +print(df_logfile)
Or did you create a new pull request for the answers?

2021-08-31 06:38 UTC, ranjanikrishnan commented on log.py
> +group_operationtype1 = df_logfile.groupby("type")
Rename to `group_operation_type` :)

2021-08-31 06:38 UTC, ranjanikrishnan commented on log.py
> +mean_operationtype = group_operationtype1.mean()
Here as well, ideally try to follow the naming conventions like [here](https://realpython.com/python-pep8/),

rename to `mean_operation_type` :)

2021-08-31 06:38 UTC, ranjanikrishnan commented on log.py
> +print(df_logfile.type.value_counts().query)
You could assign `df_logfile.type.value_counts()` to a variable and reuse that in the later lines like:

```
log_file_value_counts = df_logfile.type.value_counts()
print(f'Queries: {log_file_value_counts.query}')
print(f'Mutation: {log_file_value_counts.mutation}')
print(f'Subscription: {log_file_value_counts.subscription}')
```

Note: the print above uses an improved string formatting which is considered a best practice:)
check f-Strings [here](https://realpython.com/python-f-strings/)

2021-08-31 06:54 UTC, madhavhugar requested changes
don't forget to add a README.md file

2021-08-31 06:57 UTC, madhavhugar commented
`pip3 freeze > requirements.txt` run this in the project directory when your virtualenv is activated

2021-09-01 05:40 UTC, merged